version: '3'

services:

  app:
    container_name: app-dev
    image: app-dev
    build:
      context:  ./../client
    ports:
      - 3000:3000

  server:
    build:
      context: ./../server
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
      POSTGRES_DB: streaming
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/